export type DayId =
  | "monday"
  | "tuesday"
  | "wednesday"
  | "thursday"
  | "friday"
  | "saturday"
  | "sunday";

export type DayType = "training" | "rest";

export type Exercise = {
  id: string;
  name: string;
  sets: string;
  group: string;
  cue: string;
  setup: string;
  feel: string;
  alternative: string;
};

export type TrainingDay = {
  id: DayId;
  label: string;
  shortLabel: string;
  focus: string;
  type: DayType;
  companion: string;
  cardio: string;
  duration: string;
  notes: string;
  warmup: string[];
  exercises: Exercise[];
};

const legsWarmup = [
  "2 rounds de 10 bodyweight squats con pausa corta abajo.",
  "10 leg swings al frente y 10 laterales por pierna.",
  "8 hip hinges lentos para activar gluteo y femoral.",
  "20 segundos de estiramiento de tobillo y cadera por lado.",
];

const upperWarmup = [
  "10 circulos de hombro hacia adelante y 10 hacia atras.",
  "10 band pull-aparts o aperturas sin peso si no hay banda.",
  "8 scapular retractions lentas para despertar la espalda.",
  "1 serie ligera del primer empuje y del primer jalon del dia.",
];

const pushWarmup = [
  "10 shoulder rolls por lado.",
  "10 elevaciones laterales sin peso o con peso muy ligero.",
  "8 repeticiones lentas de press en maquina vacia o muy ligera.",
  "20 segundos de movilidad de pecho y triceps por lado.",
];

const pullWarmup = [
  "10 retracciones escapulares lentas.",
  "10 curls ligeros para calentar codo y antebrazo.",
  "1 serie suave de lat pulldown y 1 serie suave de cable row.",
  "20 segundos de movilidad de muñeca y hombro por lado.",
];

export const weeklySplit: TrainingDay[] = [
  {
    id: "monday",
    label: "Lunes",
    shortLabel: "Lun",
    focus: "Piernas",
    type: "training",
    companion: "Solo",
    cardio: "20 min de escaladora a baja intensidad",
    duration: "55-70 min + cardio",
    notes: "Base pesada de piernas. Abres con biserie de femoral y pantorrilla, y cierras con abductores al fallo. El jueves repite la misma estructura.",
    warmup: legsWarmup,
    exercises: [
      {
        id: "leg-curl",
        name: "Leg curl (biserie con calf raises)",
        sets: "3 x 8-10",
        group: "Femoral",
        cue: "Sube fuerte, baja lento y no despegues la cadera del apoyo. Al terminar cada set, pasas directo a pantorrillas.",
        setup: "Ajusta la maquina para que el rodillo quede justo encima del talon y la rodilla alineada con el eje.",
        feel: "Debes sentir el trabajo en la parte de atras del muslo.",
        alternative: "Si la maquina esta ocupada, haz femoral con mancuerna sujetada entre los pies solo si puedes hacerlo con control.",
      },
      {
        id: "calf-raises",
        name: "Calf raises (biserie con leg curl)",
        sets: "3 x 10",
        group: "Pantorrilla",
        cue: "Sube todo lo que puedas sobre la punta del pie, aprieta arriba y baja controlado. Va pegado al leg curl antes de descansar.",
        setup: "Usa la maquina de calf raises o una prensa adaptada, con el metatarso apoyado y el talon libre para bajar.",
        feel: "Debe sentirse en la pantorrilla, con estiramiento abajo y contraccion arriba.",
        alternative: "Si no hay maquina, haz calf raises de pie con mancuerna o en Smith.",
      },
      {
        id: "romanian-deadlift",
        name: "Romanian deadlift",
        sets: "2 x 8",
        group: "Femoral / gluteo",
        cue: "Cadera hacia atras, pecho orgulloso y recorrido corto pero limpio.",
        setup: "Toma dos mancuernas o la barra que uses, pies al ancho de cadera y rodillas ligeramente flexionadas.",
        feel: "Se debe sentir estiramiento en femoral y tension en gluteo, no dolor en la espalda baja.",
        alternative: "Si ese dia no te sientes seguro, cambia por back extension enfocada en gluteo y femoral.",
      },
      {
        id: "smith-squat",
        name: "Smith machine squats",
        sets: "3 x 8",
        group: "Cuadriceps / gluteo",
        cue: "Baja con control y empuja el piso con todo el pie.",
        setup: "Coloca la barra de Smith a la altura del pecho, pies un poco delante de la barra y abdomen firme antes de bajar.",
        feel: "Principalmente cuadriceps y gluteo; la espalda debe sentirse estable, no cargada.",
        alternative: "Si la Smith esta ocupada, usa leg press pesada como reemplazo principal.",
      },
      {
        id: "bulgarian-split-squat",
        name: "Bulgarian split squat",
        sets: "2 x 8 por pierna",
        group: "Cuadriceps / gluteo",
        cue: "Paso estable, torso firme y rodilla siguiendo la punta del pie.",
        setup: "Apoya el empeine trasero en un banco bajo y deja la pierna de trabajo suficientemente adelantada para bajar recto.",
        feel: "Debe quemar fuerte la pierna de adelante, sobre todo cuadriceps y gluteo.",
        alternative: "Si ese dia no quieres pelear con el equilibrio, cambia por split squat sin banco o zancada estatica.",
      },
      {
        id: "leg-extension",
        name: "Leg extension",
        sets: "2 x 8-10",
        group: "Cuadriceps",
        cue: "Aprieta arriba un instante y no rebotes en la bajada.",
        setup: "Ajusta el respaldo y el rodillo para que quede sobre el empeine con rodilla alineada al eje.",
        feel: "Debe aislar el cuadriceps en la parte frontal del muslo.",
        alternative: "Si no hay maquina, usa goblet squat con tempo lento.",
      },
      {
        id: "hip-thrust",
        name: "Hip thrust",
        sets: "2-3 x 8",
        group: "Gluteo",
        cue: "Sube con cadera, bloquea arriba con gluteo y no hiperextiendas la espalda.",
        setup: "Apoya la parte alta de la espalda en el banco o usa la maquina, pies firmes y barbilla ligeramente hacia abajo.",
        feel: "El gluteo debe llevarse casi todo el trabajo.",
        alternative: "Si la estacion no esta libre, haz glute bridge pesado en el piso o en banco.",
      },
      {
        id: "abductor-finisher",
        name: "Abductor machine finisher",
        sets: "1 x fallo",
        group: "Abductores / gluteo medio",
        cue: "Abre con control, sostén un instante y lleva ese ultimo set hasta el fallo tecnico.",
        setup: "Ajusta el asiento para que la espalda quede pegada y las rodillas empujen contra los pads en una apertura comoda.",
        feel: "Se debe quemar la parte lateral del gluteo y la cadera externa.",
        alternative: "Si no hay maquina libre, usa abducciones con banda como finisher.",
      },
    ],
  },
  {
    id: "tuesday",
    label: "Martes",
    shortLabel: "Mar",
    focus: "Upper Body",
    type: "training",
    companion: "Solo",
    cardio: "20 min de escaladora a baja intensidad",
    duration: "75-90 min + cardio",
    notes: "El dia mas largo. Llega comido, hidratado y sin ir con prisa.",
    warmup: upperWarmup,
    exercises: [
      {
        id: "dumbbell-shoulder-press",
        name: "Dumbbell shoulder press",
        sets: "2 x 8",
        group: "Hombro frontal",
        cue: "Empuja vertical, con abdomen firme y sin arquear la espalda.",
        setup: "Siéntate con respaldo, mancuernas a la altura de la oreja y pies bien plantados.",
        feel: "Debe sentirse en hombro frontal y algo de tricep.",
        alternative: "Press militar en maquina si quieres mas estabilidad.",
      },
      {
        id: "cable-lateral-raises",
        name: "Cable lateral raises",
        sets: "2 x 10 por brazo",
        group: "Hombro lateral",
        cue: "Brazo semirrígido y subida limpia hasta la altura del hombro.",
        setup: "Usa polea baja con agarre simple y colócate de lado a la torre.",
        feel: "Se debe sentir en la parte lateral del hombro, no en el cuello.",
        alternative: "Elevaciones laterales con mancuerna.",
      },
      {
        id: "machine-incline-chest-press",
        name: "Machine incline chest press",
        sets: "3 x 8",
        group: "Pecho superior",
        cue: "Escapulas atras y empuje parejo.",
        setup: "Ajusta asiento para que las asas queden a la linea media del pecho alto.",
        feel: "Pecho superior y algo de hombro frontal.",
        alternative: "Press inclinado con mancuernas si no hay maquina.",
      },
      {
        id: "machine-chest-flyes",
        name: "Machine chest flyes",
        sets: "2 x 8",
        group: "Pecho",
        cue: "Cierra como abrazando y vuelve sin dejar caer el peso.",
        setup: "Ajusta asiento para que codos y manos salgan a la altura del pecho.",
        feel: "Pecho en estiramiento y cierre.",
        alternative: "Pec deck o fly con mancuernas en banco plano.",
      },
      {
        id: "lat-pulldown",
        name: "Lat pulldown",
        sets: "2 x 8",
        group: "Espalda",
        cue: "Codos hacia abajo y pecho arriba, sin jalar solo con biceps.",
        setup: "Ajusta el soporte de muslos y toma la barra un poco mas ancho que hombros.",
        feel: "Dorsal ancho y espalda alta.",
        alternative: "Assisted pull-up o high row si esa maquina esta libre.",
      },
      {
        id: "cable-rows",
        name: "Cable rows",
        sets: "2 x 8 por brazo",
        group: "Espalda media",
        cue: "Jala hacia la cadera y aprieta la escapula atras.",
        setup: "Usa polea media o baja con agarre individual y mantén torso estable.",
        feel: "Espalda media, dorsal y algo de biceps.",
        alternative: "Remo con mancuerna apoyado en banco.",
      },
      {
        id: "barbell-cable-rows",
        name: "Barbell cable rows",
        sets: "2 x 8",
        group: "Espalda",
        cue: "Recorrido firme, torso quieto y sin impulso.",
        setup: "Conecta barra recta a polea baja, pies firmes y pecho alto.",
        feel: "Espalda media y dorsal.",
        alternative: "Seated row en maquina o remo con barra T si hay soporte.",
      },
      {
        id: "reverse-machine-flyes-upper",
        name: "Reverse machine flyes",
        sets: "1 x 10",
        group: "Deltoide posterior",
        cue: "Abre con hombro trasero, no con trapecio.",
        setup: "Siéntate mirando al respaldo o usa la configuracion de deltoide posterior.",
        feel: "Hombro trasero y parte alta de la espalda.",
        alternative: "Rear delt fly con mancuernas ligeras.",
      },
      {
        id: "cable-overhead-tricep-extension",
        name: "Cable overhead tricep extension",
        sets: "2 x 8",
        group: "Triceps",
        cue: "Codos quietos y extension completa.",
        setup: "Usa cuerda en polea alta, ponte de espaldas a la maquina y fija los codos arriba.",
        feel: "Triceps, sobre todo la cabeza larga.",
        alternative: "Overhead tricep extension con mancuerna.",
      },
      {
        id: "katana-tricep-extension",
        name: "Katana tricep extension",
        sets: "2 x 8",
        group: "Triceps",
        cue: "Mantén el codo alto y evita girar el torso.",
        setup: "Polea alta con agarre simple, brazo por encima de la cabeza y recorrido diagonal.",
        feel: "Triceps en extension larga.",
        alternative: "Kickback con mancuerna o extension por encima de la cabeza con una mancuerna.",
      },
      {
        id: "dumbbell-incline-curl",
        name: "Dumbbell incline curl",
        sets: "2 x 8",
        group: "Biceps",
        cue: "Sube limpio, con codo atras y sin columpio.",
        setup: "Banco inclinado, espalda apoyada y brazos cayendo a los lados.",
        feel: "Biceps con mucho estiramiento abajo.",
        alternative: "Curl alterno de pie si no hay banco libre.",
      },
      {
        id: "dumbbell-hammer-curl",
        name: "Dumbbell hammer curl",
        sets: "2 x 8",
        group: "Biceps / braquial",
        cue: "Muñeca neutra y codo pegado al torso.",
        setup: "Hazlo de pie o sentado con mancuernas a los lados.",
        feel: "Braquial, antebrazo y biceps.",
        alternative: "Hammer curl en cuerda si la polea esta libre y quieres variar.",
      },
    ],
  },
  {
    id: "wednesday",
    label: "Miércoles",
    shortLabel: "Mie",
    focus: "Descanso",
    type: "rest",
    companion: "Libre",
    cardio: "No",
    duration: "Recuperacion",
    notes: "Recarga, come bien y llega fresco al jueves.",
    warmup: [],
    exercises: [],
  },
  {
    id: "thursday",
    label: "Jueves",
    shortLabel: "Jue",
    focus: "Piernas",
    type: "training",
    companion: "Solo",
    cardio: "20 min de escaladora a baja intensidad",
    duration: "55-70 min + cardio",
    notes: "Misma base del lunes: biserie de femoral y pantorrilla al inicio, abductores al fallo al final.",
    warmup: legsWarmup,
    exercises: [
      {
        id: "leg-curl-thursday",
        name: "Leg curl (biserie con calf raises)",
        sets: "3 x 8-10",
        group: "Femoral",
        cue: "Sube fuerte, baja lento y no despegues la cadera del apoyo. Al terminar cada set, pasas directo a pantorrillas.",
        setup: "Ajusta la maquina para que el rodillo quede justo encima del talon y la rodilla alineada con el eje.",
        feel: "Debes sentir el trabajo en la parte de atras del muslo.",
        alternative: "Si la maquina esta ocupada, haz femoral con mancuerna sujetada entre los pies solo si puedes hacerlo con control.",
      },
      {
        id: "calf-raises-thursday",
        name: "Calf raises (biserie con leg curl)",
        sets: "3 x 10",
        group: "Pantorrilla",
        cue: "Sube todo lo que puedas sobre la punta del pie, aprieta arriba y baja controlado. Va pegado al leg curl antes de descansar.",
        setup: "Usa la maquina de calf raises o una prensa adaptada, con el metatarso apoyado y el talon libre para bajar.",
        feel: "Debe sentirse en la pantorrilla, con estiramiento abajo y contraccion arriba.",
        alternative: "Si no hay maquina, haz calf raises de pie con mancuerna o en Smith.",
      },
      {
        id: "romanian-deadlift-thursday",
        name: "Romanian deadlift",
        sets: "2 x 8",
        group: "Femoral / gluteo",
        cue: "Cadera hacia atras, pecho orgulloso y recorrido corto pero limpio.",
        setup: "Toma dos mancuernas o la barra que uses, pies al ancho de cadera y rodillas ligeramente flexionadas.",
        feel: "Se debe sentir estiramiento en femoral y tension en gluteo, no dolor en la espalda baja.",
        alternative: "Si ese dia no te sientes seguro, cambia por back extension enfocada en gluteo y femoral.",
      },
      {
        id: "smith-squat-thursday",
        name: "Smith machine squats",
        sets: "3 x 8",
        group: "Cuadriceps / gluteo",
        cue: "Baja con control y empuja el piso con todo el pie.",
        setup: "Coloca la barra de Smith a la altura del pecho, pies un poco delante de la barra y abdomen firme antes de bajar.",
        feel: "Principalmente cuadriceps y gluteo; la espalda debe sentirse estable, no cargada.",
        alternative: "Si la Smith esta ocupada, usa leg press pesada como reemplazo principal.",
      },
      {
        id: "bulgarian-split-squat-thursday",
        name: "Bulgarian split squat",
        sets: "2 x 8 por pierna",
        group: "Cuadriceps / gluteo",
        cue: "Paso estable, torso firme y rodilla siguiendo la punta del pie.",
        setup: "Apoya el empeine trasero en un banco bajo y deja la pierna de trabajo suficientemente adelantada para bajar recto.",
        feel: "Debe quemar fuerte la pierna de adelante, sobre todo cuadriceps y gluteo.",
        alternative: "Si ese dia no quieres pelear con el equilibrio, cambia por split squat sin banco o zancada estatica.",
      },
      {
        id: "leg-extension-thursday",
        name: "Leg extension",
        sets: "2 x 8-10",
        group: "Cuadriceps",
        cue: "Aprieta arriba un instante y no rebotes en la bajada.",
        setup: "Ajusta el respaldo y el rodillo para que quede sobre el empeine con rodilla alineada al eje.",
        feel: "Debe aislar el cuadriceps en la parte frontal del muslo.",
        alternative: "Si no hay maquina, usa goblet squat con tempo lento.",
      },
      {
        id: "hip-thrust-thursday",
        name: "Hip thrust",
        sets: "2-3 x 8",
        group: "Gluteo",
        cue: "Sube con cadera, bloquea arriba con gluteo y no hiperextiendas la espalda.",
        setup: "Apoya la parte alta de la espalda en el banco o usa la maquina, pies firmes y barbilla ligeramente hacia abajo.",
        feel: "El gluteo debe llevarse casi todo el trabajo.",
        alternative: "Si la estacion no esta libre, haz glute bridge pesado en el piso o en banco.",
      },
      {
        id: "abductor-finisher-thursday",
        name: "Abductor machine finisher",
        sets: "1 x fallo",
        group: "Abductores / gluteo medio",
        cue: "Abre con control, sostén un instante y lleva ese ultimo set hasta el fallo tecnico.",
        setup: "Ajusta el asiento para que la espalda quede pegada y las rodillas empujen contra los pads en una apertura comoda.",
        feel: "Se debe quemar la parte lateral del gluteo y la cadera externa.",
        alternative: "Si no hay maquina libre, usa abducciones con banda como finisher.",
      },
    ],
  },
  {
    id: "friday",
    label: "Viernes",
    shortLabel: "Vie",
    focus: "Push",
    type: "training",
    companion: "Con tu novia",
    cardio: "20 min de escaladora a baja intensidad",
    duration: "50-60 min + cardio",
    notes: "Dia alineado con pecho, hombros y triceps.",
    warmup: pushWarmup,
    exercises: [
      {
        id: "dumbbell-shoulder-press-friday",
        name: "Dumbbell shoulder press",
        sets: "2 x 8",
        group: "Hombro frontal",
        cue: "Sube vertical, con abdomen firme y sin arquear la espalda.",
        setup: "Siéntate con respaldo, mancuernas a la altura de la oreja y pies bien plantados.",
        feel: "Debe sentirse en hombro frontal y algo de tricep.",
        alternative: "Press militar en maquina si quieres mas estabilidad.",
      },
      {
        id: "cable-lateral-raises-friday",
        name: "Cable lateral raises",
        sets: "3 x 10 por brazo",
        group: "Hombro lateral",
        cue: "Sube con control y no balancees el torso.",
        setup: "Usa polea baja con agarre simple y colócate de lado a la torre.",
        feel: "Hombro lateral, no cuello.",
        alternative: "Elevaciones laterales con mancuerna.",
      },
      {
        id: "machine-incline-chest-press-friday",
        name: "Machine incline chest press",
        sets: "2 x 8",
        group: "Pecho superior",
        cue: "Pecho arriba y empuje simetrico.",
        setup: "Ajusta el asiento para que las asas queden en el pecho alto.",
        feel: "Pecho superior y algo de hombro frontal.",
        alternative: "Press inclinado con mancuernas.",
      },
      {
        id: "dumbbell-flat-chest-press",
        name: "Dumbbell flat chest press",
        sets: "2 x 8",
        group: "Pecho",
        cue: "Baja hasta sentir estiramiento y sube sin golpear mancuernas.",
        setup: "Banco plano, pies firmes y hombros retraidos antes de iniciar.",
        feel: "Pecho medio y triceps.",
        alternative: "Machine chest press si quieres mayor estabilidad.",
      },
      {
        id: "machine-chest-flyes-friday",
        name: "Machine chest flyes",
        sets: "2 x 8",
        group: "Pecho",
        cue: "Cierra fuerte adelante y vuelve lento.",
        setup: "Ajusta el asiento para alinear manos y pecho.",
        feel: "Pecho en cierre y estiramiento controlado.",
        alternative: "Pec deck o fly con mancuernas.",
      },
      {
        id: "cable-overhead-tricep-extension-friday",
        name: "Cable overhead tricep extension",
        sets: "2 x 8",
        group: "Triceps",
        cue: "Estira completo sin abrir demasiado los codos.",
        setup: "Usa cuerda en polea alta y mantén codos fijos arriba.",
        feel: "Triceps, sobre todo la cabeza larga.",
        alternative: "Overhead tricep extension con mancuerna.",
      },
      {
        id: "katana-tricep-extension-friday",
        name: "Katana tricep extension",
        sets: "2 x 8",
        group: "Triceps",
        cue: "Recorrido limpio, sin girar el torso para ayudar el peso.",
        setup: "Polea alta con agarre simple y brazo elevado en diagonal.",
        feel: "Triceps en el tramo largo del movimiento.",
        alternative: "Kickback con mancuerna o extension por encima de la cabeza.",
      },
    ],
  },
  {
    id: "saturday",
    label: "Sábado",
    shortLabel: "Sab",
    focus: "Pull",
    type: "training",
    companion: "Rutina primero, cardio luego con tu novia",
    cardio: "20 min de escaladora a baja intensidad",
    duration: "55-65 min + cardio",
    notes: "Haz el pull completo y luego cierras con el cardio en pareja.",
    warmup: pullWarmup,
    exercises: [
      {
        id: "lat-pulldown-saturday",
        name: "Lat pulldown",
        sets: "2 x 8",
        group: "Espalda",
        cue: "Codos abajo y pecho estable al frente.",
        setup: "Ajusta el soporte de muslos y toma la barra un poco mas ancho que hombros.",
        feel: "Dorsal ancho y parte alta de la espalda.",
        alternative: "Assisted pull-up o high row.",
      },
      {
        id: "cable-rows-saturday",
        name: "Cable rows",
        sets: "2 x 8 por brazo",
        group: "Espalda media",
        cue: "Jala hacia la cadera y aprieta atras.",
        setup: "Usa polea media o baja con agarre individual y mantén torso estable.",
        feel: "Espalda media y dorsal.",
        alternative: "Remo con mancuerna apoyado en banco.",
      },
      {
        id: "barbell-cable-rows-saturday",
        name: "Barbell cable rows",
        sets: "2 x 8",
        group: "Espalda",
        cue: "Nada de impulso con el torso.",
        setup: "Conecta barra recta a polea baja, pecho alto y abdomen firme.",
        feel: "Espalda media y dorsal.",
        alternative: "Seated row en maquina.",
      },
      {
        id: "upright-single-arm-rows",
        name: "Upright single arm rows",
        sets: "2 x 8",
        group: "Espalda alta / trapecio",
        cue: "Sube con control y no encogas el hombro de golpe.",
        setup: "Hazlo con polea o mancuerna, brazo por delante del cuerpo y subida controlada.",
        feel: "Trapecio alto, deltoide lateral y parte alta de la espalda.",
        alternative: "High pull ligero con mancuerna o cable.",
      },
      {
        id: "reverse-machine-flyes-saturday",
        name: "Reverse machine flyes",
        sets: "2 x 10",
        group: "Deltoide posterior",
        cue: "Abre amplio y siente el hombro trasero.",
        setup: "Siéntate mirando al respaldo y mantén pecho pegado al apoyo.",
        feel: "Hombro trasero y espalda alta.",
        alternative: "Rear delt fly con mancuernas ligeras.",
      },
      {
        id: "dumbbell-shrugs",
        name: "Dumbbell shrugs",
        sets: "2 x 8",
        group: "Trapecio",
        cue: "Eleva recto hacia arriba, sin rodar los hombros.",
        setup: "Ponte de pie con mancuernas a los lados y cuello largo.",
        feel: "Trapecio superior.",
        alternative: "Shrugs en maquina Smith si no hay mancuernas disponibles.",
      },
      {
        id: "dumbbell-incline-curl-saturday",
        name: "Dumbbell incline curl",
        sets: "1 x 8",
        group: "Biceps",
        cue: "Mantén el brazo atras y sube sin impulso.",
        setup: "Banco inclinado, espalda apoyada y codos colgando hacia atras.",
        feel: "Biceps en estiramiento y cierre.",
        alternative: "Curl alterno de pie.",
      },
      {
        id: "preacher-curl",
        name: "Preacher curl en maquina o mancuerna",
        sets: "2 x 8",
        group: "Biceps",
        cue: "No despegues el brazo del apoyo.",
        setup: "Ajusta el soporte para que la axila quede bien fijada arriba del pad.",
        feel: "Biceps aislado, sobre todo en la parte media del recorrido.",
        alternative: "Curl spider o curl alterno sentado.",
      },
      {
        id: "dumbbell-hammer-curl-saturday",
        name: "Dumbbell hammer curl",
        sets: "2 x 8",
        group: "Biceps / braquial",
        cue: "Muñeca neutra y subida firme.",
        setup: "Hazlo de pie o sentado con mancuernas a los lados.",
        feel: "Braquial, antebrazo y biceps.",
        alternative: "Hammer curl con cuerda.",
      },
    ],
  },
  {
    id: "sunday",
    label: "Domingo",
    shortLabel: "Dom",
    focus: "Descanso",
    type: "rest",
    companion: "Libre",
    cardio: "No",
    duration: "Recuperacion",
    notes: "Dia completo para soltar fatiga y recargar.",
    warmup: [],
    exercises: [],
  },
];

export const dayOrder: DayId[] = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

export function getDayById(dayId: DayId) {
  return weeklySplit.find((day) => day.id === dayId)!;
}

export function weekdayToDayId(weekday: number): DayId {
  return dayOrder[(weekday + 6) % 7];
}
